name: 🐛 Bug Report
description: Report a problem with the WinCC OA VS Code Extension
title: "[Bug]: "
labels: ["bug", "needs-triage"]
projects: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! 🐛
        
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (Extension completely unusable)
        - High (Major functionality broken)
        - Medium (Feature partially broken)
        - Low (Minor issue or cosmetic)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened instead

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened

  - type: textarea
    id: error-logs
    attributes:
      label: Error Messages/Logs
      description: Copy any error messages or relevant log output
      placeholder: Paste error messages, stack traces, or log output here
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: You can paste screenshots directly here

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: What version of the WinCC OA extension are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: VS Code Version
      description: What version of VS Code are you using?
      placeholder: "e.g., 1.94.0"
    validations:
      required: true

  - type: dropdown
    id: winccoa-version
    attributes:
      label: WinCC OA Version
      description: Which WinCC OA version are you using?
      options:
        - "3.21"
        - "3.20"
        - "3.19"
        - "3.18"
        - "Multiple versions"
        - "Not applicable"
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 11
        - Windows 10
        - Windows Server 2022
        - Windows Server 2019
        - Linux (specify in additional context)
        - Other
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help us understand the issue

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true